-- ADREGAMDI --

-- 1. 회원정보 --

-- (1) 테이블 생성 --
DROP TABLE USER_INFO PURGE;
CREATE TABLE USER_INFO
(
    USER_NO       NUMBER          CONSTRAINT USER_INFO_PK PRIMARY KEY, 
    USER_NAME     VARCHAR2(15), 
    USER_ID       VARCHAR2(50)    UNIQUE, 
    USER_PW       VARCHAR2(100), 
    USER_EMAIL    VARCHAR2(50)    NOT NULL, 
    USER_PHONE    VARCHAR2(15)    NOT NULL, 
    USER_PROVIDER NUMBER          NOT NULL
);

-- (2) 시퀀스 생성 --
DROP SEQUENCE USER_INFO_SEQ;
CREATE SEQUENCE USER_INFO_SEQ
START WITH 1
INCREMENT BY 1;

-- (3) 특이사항 --

-- 회원탈퇴를 위해 반드시 필요한 쿼리문

-- 외래키 컬럼 삭제
ALTER TABLE [각 게시판 테이블] DROP CONSTRAINT [외래키 이름];

-- ON DELETE CASCADE 를 적용한 외래키 재생성
ALTER TABLE [각 게시판 테이블] ADD CONSTRAINT [외래키 이름] FOREIGN KEY ([외래키 자식 컬럼])
REFERENCES USER_INFO(USER_NO) ON DELETE CASCADE;

-- PROVIDER(0) : 관리자(ADMINISTRATOR)
UPDATE USER_INFO SET USER_PROVIDER = 0 WHERE USER_NO = 1;

-- 2. 공지사항 --

-- (1) 테이블 생성 --
DROP TABLE NOTICE PURGE;
CREATE TABLE NOTICE(
    NOTICE_NO        NUMBER           CONSTRAINT NOTICE_PK PRIMARY KEY, 
    NOTICE_USER_NO   NUMBER           CONSTRAINT NOTICE_FK REFERENCES USER_INFO(USER_NO),
    NOTICE_TITLE     VARCHAR2(100)    NOT NULL, 
    NOTICE_CNT       NUMBER           NOT NULL, 
    NOTICE_DATE      DATE             NOT NULL, 
    NOTICE_CONTENT   VARCHAR2(4000)   NOT NULL
);

-- (2) 시퀀스 생성 --
DROP SEQUENCE NOTICE_SEQ;
CREATE SEQUENCE NOTICE_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE notice DROP CONSTRAINT notice_fk;

ALTER TABLE notice ADD CONSTRAINT notice_fk FOREIGN KEY (notice_user_no)
REFERENCES USER_INFO(user_no) ON DELETE CASCADE;

-- 3. 자유게시판 --

-- (1) 테이블 생성 --

-- FREEDOMBOARD
DROP TABLE FREEDOMBOARD PURGE;
CREATE TABLE FREEDOMBOARD (
    FREE_NO        NUMBER            CONSTRAINT FREEDOMBOARD_PK PRIMARY KEY,
    FREE_WRITER    NUMBER            CONSTRAINT FREEDOMBOARD_FK REFERENCES USER_INFO(USER_NO),
    FREE_TITLE     VARCHAR2(300)     NOT NULL,
    FREE_CNT       NUMBER            NOT NULL,
    FREE_DATE      DATE              NOT NULL,
    FREE_CONTENT   VARCHAR2(4000)    NOT NULL
);

-- FREEDOMREPLY
DROP TABLE FREEDOMREPLY PURGE;
CREATE TABLE FREEDOMREPLY (
    REPLY_NUM       NUMBER           CONSTRAINT FREEDOMREPLY_PK PRIMARY KEY,
    FREEDOM_NUM     NUMBER           CONSTRAINT FREEDOMREPLY_FK REFERENCES FREEDOMBOARD(FREE_NO),
    REPLY_WRITER    VARCHAR2(100)    NOT NULL,
    REPLY_CONTENT   VARCHAR2(1000)   NOT NULL,
    REPLY_DATE      DATE             NOT NULL
);

-- (2) 시퀀스 생성 --

DROP SEQUENCE FREEDOM_REPLY_SEQ;
CREATE SEQUENCE FREEDOM_REPLY_SEQ
START WITH 1
INCREMENT BY 1;

DROP SEQUENCE CONTENT_CNT_SEQ;
CREATE SEQUENCE CONTENT_CNT_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE FREEDOMBOARD DROP CONSTRAINT FREEDOMBOARD_FK;

ALTER TABLE FREEDOMBOARD ADD CONSTRAINT FREEDOMBOARD_FK FOREIGN KEY (free_writer)
REFERENCES USER_INFO(user_no) ON DELETE CASCADE;

-- 4. 여행지 --

SELECT ROWNUM, LIKE_IDX, CONTENT_ID, LIKE_CNT, REVIEW_CNT 
FROM (SELECT * FROM SPOT_INFO ORDER BY LIKE_CNT DESC)
WHERE ROWNUM <= 3;


-- (1) 테이블 생성 --

-- SPOT_INFO
DROP TABLE SPOT_INFO PURGE;
CREATE TABLE SPOT_INFO (
    LIKE_IDX     NUMBER         CONSTRAINT LIKE_PK PRIMARY KEY,
    CONTENT_ID   VARCHAR2(10)   NOT NULL,
    LIKE_CNT     NUMBER,
    REVIEW_CNT   NUMBER
);

-- REVIEW_INFO
DROP TABLE REVIEW_INFO PURGE;
CREATE TABLE REVIEW_INFO (
    REVIEW_IDX       NUMBER          CONSTRAINT REVIEW_PK PRIMARY KEY,
    CONTENT_ID       VARCHAR2(10)    NOT NULL,
    USER_NO          NUMBER          CONSTRAINT REVIEW_FK2 REFERENCES USER_INFO(USER_NO),
    USER_NAME        VARCHAR2(15)    NOT NULL,
    REVIEW_DATE      VARCHAR2(100)   NOT NULL,
    REVIEW_CONTENT   VARCHAR2(200)   NOT NULL
);

-- (2) 시퀀스 생성 --

DROP SEQUENCE SPOT_SEQ;
CREATE SEQUENCE SPOT_SEQ
START WITH 1
INCREMENT BY 1;

DROP SEQUENCE REVIEW_SEQ;
CREATE SEQUENCE REVIEW_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE REVIEW_INFO DROP CONSTRAINT REVIEW_FK2;

ALTER TABLE REVIEW_INFO ADD CONSTRAINT REVIEW_FK2 FOREIGN KEY (USER_NO)
REFERENCES USER_INFO(user_no) ON DELETE CASCADE;


-- 5. 여행 일정 만들기 --

-- (1) 테이블 생성 --

-- PLAN
DROP TABLE PLAN PURGE;
CREATE TABLE PLAN (
    PLAN_NO        NUMBER           CONSTRAINT PLAN_PK PRIMARY KEY,
    USER_NO        NUMBER           CONSTRAINT PLAN_FK REFERENCES USER_INFO(USER_NO),
    PLAN_TITLE     VARCHAR2(200)    NOT NULL,
    PLAN_INFO      VARCHAR2(1000)   NOT NULL,
    PLAN_IMG       VARCHAR(300)     NOT NULL,
    PLAN_PRIVATE   VARCHAR(1)       DEFAULT 'N'
);

ALTER TABLE PLAN DROP CONSTRAINT PLAN_FK;

ALTER TABLE PLAN ADD CONSTRAINT PLAN_FK FOREIGN KEY (USER_NO)
REFERENCES USER_INFO(user_no) ON DELETE CASCADE;

-- PLAN_IMG
DROP TABLE PLAN_IMG PURGE;
CREATE TABLE PLAN_IMG (
    PLAN_NO    NUMBER          CONSTRAINT PLAN_IMG_FK REFERENCES PLAN(PLAN_NO),
    USER_NO    NUMBER          NOT NULL,
    PLAN_IMG   VARCHAR2(300)   NOT NULL,
    REGDATE    DATE            NOT NULL
);

ALTER TABLE PLAN_IMG DROP CONSTRAINT PLAN_IMG_FK;

ALTER TABLE PLAN_IMG ADD CONSTRAINT PLAN_IMG_FK FOREIGN KEY (PLAN_NO)
REFERENCES PLAN(PLAN_NO) ON DELETE CASCADE;

-- USER_PLAN
DROP TABLE USER_PLAN PURGE;
CREATE TABLE USER_PLAN (
    PLAN_NO          NUMBER           CONSTRAINT USER_PLAN_FK REFERENCES PLAN(PLAN_NO),
    USER_NO          NUMBER,
    TITLE            VARCHAR2(200),
    CONTENTID        VARCHAR2(10),
    CONTENTTYPEID    VARCHAR2(5),
    ADDR             VARCHAR2(200),
    IMG_SRC          VARCHAR2(300),
    MAPX             VARCHAR2(20),
    MAPY             VARCHAR2(20),
    PLANDATE         VARCHAR2(30),
    PLANDAY          VARCHAR2(30),
    PLANTOTALDATE    VARCHAR2(30),
    STARTDATE        VARCHAR2(20),
    ENDDATE          VARCHAR2(20),
    DESCRIPT         VARCHAR2(1000), 
    IS_INSERTAFTER   VARCHAR(1)       DEFAULT 'N',
    ISACC            VARCHAR(1)       DEFAULT 'N'
);

-- (2) 시퀀스 생성 --

DROP SEQUENCE PLAN_SEQ;
CREATE SEQUENCE PLAN_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE USER_PLAN DROP CONSTRAINT USER_PLAN_FK;

ALTER TABLE USER_PLAN ADD CONSTRAINT USER_PLAN_FK FOREIGN KEY (PLAN_NO)
REFERENCES PLAN(PLAN_NO) ON DELETE CASCADE;

-- 6. 동행 게시판

-- (1) 테이블 생성 --

-- TOGETHER
DROP TABLE TOGETHER PURGE;
CREATE TABLE TOGETHER(
    TO_NO          NUMBER           CONSTRAINT TOGETHER_PK PRIMARY KEY,                     
    TO_WRITER_NO   NUMBER           CONSTRAINT TOGETHER_FK1 REFERENCES USER_INFO(USER_NO),  
    TO_WRITER      VARCHAR2(50)     CONSTRAINT TOGETHER_FK2 REFERENCES USER_INFO(USER_ID),  
    TO_TITLE       VARCHAR2(300)    NOT NULL,                                                
    TO_PLACE       VARCHAR2(300)    NOT NULL,                                             
    TO_PLACE_NAME  VARCHAR2(100)    NOT NULL,
    TO_CONTENT     VARCHAR2(4000)   NOT NULL,                                              
    TO_DATE        DATE             NOT NULL,                                            
    TO_CURR        NUMBER           DEFAULT '1',                                          
    TO_TOTAL       NUMBER           NOT NULL,                                           
    TO_MEET        VARCHAR2(100)    NOT NULL,                                             
    TO_STATE       NUMBER           NOT NULL                                              
);

ALTER TABLE TOGETHER DROP CONSTRAINT together_fk1;

ALTER TABLE TOGETHER ADD CONSTRAINT together_fk1 FOREIGN KEY (TO_WRITER_NO)
REFERENCES USER_INFO(user_no) ON DELETE CASCADE;

ALTER TABLE TOGETHER DROP CONSTRAINT together_fk2;

ALTER TABLE TOGETHER ADD CONSTRAINT together_fk2 FOREIGN KEY (TO_WRITER)
REFERENCES USER_INFO(user_id) ON DELETE CASCADE;

-- TOGETHERREPLY
DROP TABLE TOGETHERREPLY PURGE;
CREATE TABLE TOGETHERREPLY (
    REPLY_NUM       NUMBER           CONSTRAINT TOGETHERREPLY_PK PRIMARY KEY,
    TOGETHER_NUM    NUMBER           CONSTRAINT TOGETHERREPLY_FK REFERENCES TOGETHER(TO_NO),
    REPLY_WRITER    VARCHAR2(100)    NOT NULL,
    REPLY_CONTENT   VARCHAR2(1000)   NOT NULL,
    REPLY_DATE      DATE             NOT NULL
);

-- SUBSCRIPTION
DROP TABLE SUBSCRIPTION PURGE;
CREATE TABLE SUBSCRIPTION (
    SUB_NO          NUMBER  CONSTRAINT SUBSCRIPTION_PK PRIMARY KEY,
    TO_NO           NUMBER  CONSTRAINT SUBSCRIPTION_FK REFERENCES TOGETHER(TO_NO),
    TO_WRITER_NO    NUMBER,
    SUB_MESSAGE     VARCHAR2(500),
    SUB_WRITER      NUMBER,
    SUB_STATUS      VARCHAR(1) DEFAULT '0',
    SUB_DATE        DATE
);

-- CHATROOM
DROP TABLE CHATROOM PURGE;
CREATE TABLE CHATROOM(
    TO_NO           NUMBER,   
    TO_WRITER_NO    NUMBER,  
    USER1           NUMBER   DEFAULT '0',
    USER2           NUMBER   DEFAULT '0',
    USER3           NUMBER   DEFAULT '0'
);

-- (2) 시퀀스 생성 --

DROP SEQUENCE TOGETHER_SEQ;
CREATE SEQUENCE TOGETHER_SEQ
START WITH 1
INCREMENT BY 1;

DROP SEQUENCE TOGETHER_REPLY_SEQ;
CREATE SEQUENCE TOGETHER_REPLY_SEQ
START WITH 1
INCREMENT BY 1;

DROP SEQUENCE SUBSCRIPTION_SEQ;
CREATE SEQUENCE SUBSCRIPTION_SEQ
START WITH 1
INCREMENT BY 1;