-- USER_INFO --
DROP TABLE USER_INFO PURGE;
CREATE TABLE USER_INFO
(
    USER_NO       NUMBER          CONSTRAINT USER_INFO_PK PRIMARY KEY, 
    USER_NAME     VARCHAR2(15), 
    USER_ID       VARCHAR2(50)    UNIQUE, 
    USER_PW       VARCHAR2(100), 
    USER_EMAIL    VARCHAR2(50)    NOT NULL, 
    USER_PHONE    VARCHAR2(15)    NOT NULL, 
    USER_PROVIDER NUMBER          NOT NULL
);

DROP TABLE USER_INFO_SEQ;
CREATE SEQUENCE USER_INFO_SEQ
START WITH 1
INCREMENT BY 1;


ALTER TABLE notice DROP CONSTRAINT notice_fk;

ALTER TABLE notice ADD CONSTRAINT notice_fk FOREIGN KEY (notice_user_no)
REFERENCES USER_INFO(user_no) ON DELETE CASCADE;



-- NOTICE --
DROP TABLE NOTICE PURGE;
CREATE TABLE NOTICE(
    NOTICE_NO        NUMBER           CONSTRAINT NOTICE_PK PRIMARY KEY, 
    NOTICE_USER_NO   NUMBER           CONSTRAINT NOTICE_FK REFERENCES USER_INFO(USER_NO),
    NOTICE_TITLE     VARCHAR2(100)    NOT NULL, 
    NOTICE_CNT       NUMBER           NOT NULL, 
    NOTICE_DATE      DATE             NOT NULL, 
    NOTICE_CONTENT   VARCHAR2(4000)   NOT NULL
);

DROP TABLE NOTICE_SEQ;
CREATE SEQUENCE NOTICE_SEQ
START WITH 1
INCREMENT BY 1;



-- FREEDOMBOARD --
DROP TABLE FREEDOMBOARD PURGE;
CREATE TABLE FREEDOMBOARD (
    FREE_NO        NUMBER            CONSTRAINT FREEDOMBOARD_PK PRIMARY KEY,
    FREE_WRITER    NUMBER            CONSTRAINT FREEDOMBOARD_FK REFERENCES USER_INFO(USER_NO),
    FREE_TITLE     VARCHAR2(300)     NOT NULL,
    FREE_CNT       NUMBER            NOT NULL,
    FREE_DATE      DATE              NOT NULL,
    FREE_CONTENT   VARCHAR2(4000)    NOT NULL
);


ALTER TABLE FREEDOMBOARD DROP CONSTRAINT FREEDOMBOARD_FK;

ALTER TABLE FREEDOMBOARD ADD CONSTRAINT FREEDOMBOARD_FK FOREIGN KEY (free_writer)
REFERENCES USER_INFO(user_no) ON DELETE CASCADE;


-- FREEDOMREPLY --
DROP TABLE FREEDOMREPLY PURGE;
CREATE TABLE FREEDOMREPLY (
    REPLY_NUM       NUMBER           CONSTRAINT FREEDOMREPLY_PK PRIMARY KEY,
    FREEDOM_NUM     NUMBER           CONSTRAINT FREEDOMREPLY_FK REFERENCES FREEDOMBOARD(FREE_NO),
    REPLY_WRITER    VARCHAR2(100)    NOT NULL,
    REPLY_CONTENT   VARCHAR2(1000)   NOT NULL,
    REPLY_DATE      DATE             NOT NULL
);

DROP TABLE FREEDOM_REPLY_SEQ;
CREATE SEQUENCE FREEDOM_REPLY_SEQ
START WITH 1
INCREMENT BY 1;

DROP TABLE CONTENT_CNT_SEQ;
CREATE SEQUENCE CONTENT_CNT_SEQ
START WITH 1
INCREMENT BY 1;


-- SPOT_INFO --
DROP TABLE SPOT_INFO PURGE;
CREATE TABLE SPOT_INFO (
    LIKE_IDX     NUMBER         CONSTRAINT LIKE_PK PRIMARY KEY,
    CONTENT_ID   VARCHAR2(10)   NOT NULL,
    LIKE_CNT     NUMBER,
    REVIEW_CNT   NUMBER
);



-- REVIEW_INFO --
DROP TABLE REVIEW_INFO PURGE;
CREATE TABLE REVIEW_INFO (
    REVIEW_IDX       NUMBER          CONSTRAINT REVIEW_PK PRIMARY KEY,
    CONTENT_ID       VARCHAR2(10)    NOT NULL,
    USER_NO          NUMBER          CONSTRAINT REVIEW_FK2 REFERENCES USER_INFO(USER_NO),
    USER_NAME        VARCHAR2(15)    NOT NULL,
    REVIEW_DATE      VARCHAR2(100)   NOT NULL,
    REVIEW_CONTENT   VARCHAR2(200)   NOT NULL
);

ALTER TABLE REVIEW_INFO DROP CONSTRAINT REVIEW_FK2;

ALTER TABLE REVIEW_INFO ADD CONSTRAINT REVIEW_FK2 FOREIGN KEY (USER_NO)
REFERENCES USER_INFO(user_no) ON DELETE CASCADE;


DROP SEQUENCE SPOT_SEQ;
CREATE SEQUENCE SPOT_SEQ
START WITH 1
INCREMENT BY 1;

DROP SEQUENCE REVIEW_SEQ;
CREATE SEQUENCE REVIEW_SEQ
START WITH 1
INCREMENT BY 1;


-- PLAN --
DROP TABLE PLAN PURGE;
CREATE TABLE PLAN (
    PLAN_NO        NUMBER           CONSTRAINT PLAN_PK PRIMARY KEY,
    USER_NO        NUMBER           CONSTRAINT PLAN_FK REFERENCES USER_INFO(USER_NO),
    PLAN_TITLE     VARCHAR2(200)    NOT NULL,
    PLAN_INFO      VARCHAR2(1000)   NOT NULL,
    PLAN_IMG       VARCHAR(300)     NOT NULL,
    PLAN_PRIVATE   VARCHAR(1)       DEFAULT 'N'
);


ALTER TABLE PLAN DROP CONSTRAINT PLAN_FK;


ALTER TABLE PLAN ADD CONSTRAINT PLAN_FK FOREIGN KEY (USER_NO)
REFERENCES USER_INFO(user_no) ON DELETE CASCADE;

-- PLAN_IMG --
DROP TABLE PLAN_IMG PURGE;
CREATE TABLE PLAN_IMG (
    PLAN_NO    NUMBER          CONSTRAINT PLAN_IMG_FK REFERENCES PLAN(PLAN_NO),
    USER_NO    NUMBER          NOT NULL,
    PLAN_IMG   VARCHAR2(300)   NOT NULL,
    REGDATE    DATE            NOT NULL
);

ALTER TABLE PLAN_IMG DROP CONSTRAINT PLAN_IMG_FK;

ALTER TABLE PLAN_IMG ADD CONSTRAINT PLAN_IMG_FK FOREIGN KEY (PLAN_NO)
REFERENCES PLAN(PLAN_NO) ON DELETE CASCADE;

-- USER_PLAN --
DROP TABLE USER_PLAN PURGE;
CREATE TABLE USER_PLAN (
    PLAN_NO          NUMBER           CONSTRAINT USER_PLAN_FK REFERENCES PLAN(PLAN_NO),
    USER_NO          NUMBER,
    TITLE            VARCHAR2(200),
    CONTENTID        VARCHAR2(10),
    CONTENTTYPEID    VARCHAR2(5),
    ADDR             VARCHAR2(200),
    IMG_SRC          VARCHAR2(300),
    MAPX             VARCHAR2(20),
    MAPY             VARCHAR2(20),
    PLANDATE         VARCHAR2(30),
    PLANDAY          VARCHAR2(30),
    PLANTOTALDATE    VARCHAR2(30),
    STARTDATE        VARCHAR2(20),
    ENDDATE          VARCHAR2(20),
    DESCRIPT         VARCHAR2(1000), 
    IS_INSERTAFTER   VARCHAR(1)       DEFAULT 'N',
    ISACC            VARCHAR(1)       DEFAULT 'N'
);

ALTER TABLE USER_PLAN DROP CONSTRAINT USER_PLAN_FK;

ALTER TABLE USER_PLAN ADD CONSTRAINT USER_PLAN_FK FOREIGN KEY (PLAN_NO)
REFERENCES PLAN(PLAN_NO) ON DELETE CASCADE;


DROP SEQUENCE PLAN_SEQ;
CREATE SEQUENCE PLAN_SEQ
START WITH 1
INCREMENT BY 1;

-- TOGETHER --
DROP TABLE TOGETHER PURGE;
create table together(
    to_no       NUMBER              constraint together_pk primary key,                      -- 게시글번호
    to_writer_no   number           constraint together_fk1 references user_info(user_no),   -- 회원번호
    to_writer   varchar2(50)        constraint together_fk2 references user_info(user_id),   -- 회원번호
    to_title    varchar2(300)       not null,                                                -- 공고제목   
    to_place    varchar2(300)       not null,                                                -- 여행장소    
    to_place_name varchar2(100)     not null,
    to_content  varchar2(4000)      not null,                                                -- 공고문
    to_date     date                not null,                                                -- 작성날짜   
    to_curr     number              DEFAULT '1',                                            -- 현재인원    
    to_total    number              not null,                                                -- 모집인원   
    to_meet     varchar2(100)       not null,                                                -- 여행날짜   
    to_state    number              not null                                                 -- 공고현황   
);


ALTER TABLE TOGETHER DROP CONSTRAINT together_fk1;
ALTER TABLE TOGETHER DROP CONSTRAINT together_fk2;

ALTER TABLE TOGETHER ADD CONSTRAINT together_fk1 FOREIGN KEY (TO_WRITER_NO)
REFERENCES USER_INFO(user_no) ON DELETE CASCADE;
ALTER TABLE TOGETHER ADD CONSTRAINT together_fk2 FOREIGN KEY (TO_WRITER)
REFERENCES USER_INFO(user_id) ON DELETE CASCADE;



DROP SEQUENCE TOGETHER_SEQ;
CREATE SEQUENCE TOGETHER_SEQ
START WITH 1
INCREMENT BY 1;


DROP TABLE SUBSCRIPTION PURGE;
CREATE TABLE SUBSCRIPTION (
    sub_no      NUMBER  CONSTRAINT SUBSCRIPTION_PK PRIMARY KEY,
    to_no       NUMBER constraint SUBSCRIPTION_FK references TOGETHER(to_no),
    to_writer_no   NUMBER,
    sub_message VARCHAR2(500),
    sub_writer  NUMBER,
    sub_status  VARCHAR(1) DEFAULT '0',
    sub_date    DATE
);

DROP SEQUENCE SUBSCRIPTION_SEQ;
CREATE SEQUENCE SUBSCRIPTION_SEQ
START WITH 1
INCREMENT BY 1;



DROP TABLE CHATROOM PURGE;
CREATE TABLE CHATROOM(
    TO_NO           NUMBER,
    TO_WRITER_NO    NUMBER,
    USER1           NUMBER DEFAULT '0',
    USER2           NUMBER DEFAULT '0',
    USER3           NUMBER DEFAULT '0'
);

insert into chatroom values(1, 1, 0, 0, 0);
SELECT * FROM chatroom;
UPDATE CHATROOM SET USER1 = 0 WHERE TO_NO = 1;
delete from chatroom;


-- TOGETHERREPLY
DROP TABLE TOGETHERREPLY PURGE;
CREATE TABLE TOGETHERREPLY (
    REPLY_NUM       NUMBER           CONSTRAINT TOGETHERREPLY_PK PRIMARY KEY,
    TOGETHER_NUM    NUMBER           CONSTRAINT TOGETHERREPLY_FK REFERENCES TOGETHER(TO_NO),
    REPLY_WRITER    VARCHAR2(100)    NOT NULL,
    REPLY_CONTENT   VARCHAR2(1000)   NOT NULL,
    REPLY_DATE      DATE             NOT NULL
);


DROP SEQUENCE TOGETHER_REPLY_SEQ;
CREATE SEQUENCE TOGETHER_REPLY_SEQ
START WITH 1
INCREMENT BY 1;