-- SPOT_INFO
DROP TABLE SPOT_INFO PURGE;

CREATE TABLE SPOT_INFO (
    LIKE_IDX     NUMBER         CONSTRAINT LIKE_PK PRIMARY KEY,
    CONTENT_ID   VARCHAR2(10)   NOT NULL,
    LIKE_CNT     NUMBER,
    REVIEW_CNT   NUMBER
);

DROP SEQUENCE SPOT_SEQ;
CREATE SEQUENCE SPOT_SEQ
START WITH 1
INCREMENT BY 1;

-- 데이터 입력 --

SELECT * FROM SPOT_INFO;


UPDATE SPOT_INFO SET LIKE_CNT = 25 WHERE CONTENT_ID = '322836';
UPDATE SPOT_INFO SET LIKE_CNT = 85 WHERE CONTENT_ID = '127813';
UPDATE SPOT_INFO SET LIKE_CNT = 78 WHERE CONTENT_ID = '126438';
UPDATE SPOT_INFO SET LIKE_CNT = 70 WHERE CONTENT_ID = '126435';
UPDATE SPOT_INFO SET LIKE_CNT = 195 WHERE CONTENT_ID = '228854';
UPDATE SPOT_INFO SET LIKE_CNT = 854 WHERE CONTENT_ID = '126452';
UPDATE SPOT_INFO SET LIKE_CNT = 45 WHERE CONTENT_ID = '129617';
UPDATE SPOT_INFO SET LIKE_CNT = 748 WHERE CONTENT_ID = '141736';
UPDATE SPOT_INFO SET LIKE_CNT = 87 WHERE CONTENT_ID = '126439';
UPDATE SPOT_INFO SET LIKE_CNT = 755 WHERE CONTENT_ID = '667418';
UPDATE SPOT_INFO SET LIKE_CNT = 744 WHERE CONTENT_ID = '228853';
UPDATE SPOT_INFO SET LIKE_CNT = 78 WHERE CONTENT_ID = '126471';
UPDATE SPOT_INFO SET LIKE_CNT = 78 WHERE CONTENT_ID = '127490';
UPDATE SPOT_INFO SET LIKE_CNT = 7 WHERE CONTENT_ID = '127479';
UPDATE SPOT_INFO SET LIKE_CNT = 78 WHERE CONTENT_ID = '139008';
UPDATE SPOT_INFO SET LIKE_CNT = 74 WHERE CONTENT_ID = '126470';
UPDATE SPOT_INFO SET LIKE_CNT = 88 WHERE CONTENT_ID = '127635';
UPDATE SPOT_INFO SET LIKE_CNT = 77 WHERE CONTENT_ID = '142948';
UPDATE SPOT_INFO SET LIKE_CNT = 7 WHERE CONTENT_ID = '127336';
UPDATE SPOT_INFO SET LIKE_CNT = 123 WHERE CONTENT_ID = '127053';
UPDATE SPOT_INFO SET LIKE_CNT = 754 WHERE CONTENT_ID = '2444532';
UPDATE SPOT_INFO SET LIKE_CNT = 78 WHERE CONTENT_ID = '130474';
UPDATE SPOT_INFO SET LIKE_CNT = 54 WHERE CONTENT_ID = '128556';

commit; 

-- REVIEW_INFO
DROP TABLE REVIEW_INFO PURGE;
CREATE TABLE REVIEW_INFO (
    REVIEW_IDX       NUMBER          CONSTRAINT REVIEW_PK PRIMARY KEY,
    CONTENT_ID       VARCHAR2(10)    NOT NULL,
    USER_NO          NUMBER          CONSTRAINT REVIEW_FK2 REFERENCES USER_INFO(USER_NO),
    USER_ID        VARCHAR2(50)    NOT NULL,
    REVIEW_DATE      VARCHAR2(100)   NOT NULL,
    REVIEW_CONTENT   VARCHAR2(200)   NOT NULL
);

-- ON DELETE CASCADE (���� ����)
ALTER TABLE REVIEW_INFO DROP CONSTRAINT REVIEW_FK2;

ALTER TABLE REVIEW_INFO ADD CONSTRAINT REVIEW_FK2 FOREIGN KEY (USER_NO)
REFERENCES USER_INFO(user_no) ON DELETE CASCADE;



DROP SEQUENCE REVIEW_SEQ;
CREATE SEQUENCE REVIEW_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM REVIEW_INFO;